/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DueRecord {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'date' : Time,
  'neighborhood' : string,
  'fatherName' : string,
  'village' : string,
  'itemType' : string,
  'quantity' : bigint,
  'mobile' : string,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
  'medicineId' : bigint,
  'medicineName' : string,
}
export interface MedicineRecord {
  'id' : bigint,
  'purchasePrice' : bigint,
  'expiryDate' : Time,
  'name' : string,
  'createdAt' : Time,
  'minStockAlert' : bigint,
  'sellingPrice' : bigint,
  'itemType' : string,
  'quantity' : bigint,
  'brand' : string,
}
export interface PurchaseRecord {
  'id' : bigint,
  'supplierName' : string,
  'date' : Time,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
  'medicineId' : bigint,
  'medicineName' : string,
}
export interface SaleRecord {
  'id' : bigint,
  'customerName' : [] | [string],
  'date' : Time,
  'invoiceNumber' : bigint,
  'notes' : [] | [string],
  'quantity' : bigint,
  'brand' : string,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
  'medicineId' : bigint,
  'medicineName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addDueRecord' : ActorMethod<[DueRecord], bigint>,
  'addMedicine' : ActorMethod<[MedicineRecord], bigint>,
  'createPurchase' : ActorMethod<[PurchaseRecord], bigint>,
  'createSale' : ActorMethod<[SaleRecord], bigint>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'getAllDueRecords' : ActorMethod<[], Array<DueRecord>>,
  'getAllMedicines' : ActorMethod<[], Array<MedicineRecord>>,
  'getAllPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getAllSales' : ActorMethod<[], Array<SaleRecord>>,
  'getDueRecord' : ActorMethod<[bigint], DueRecord>,
  'getDueRecordsByStatus' : ActorMethod<[string], Array<DueRecord>>,
  'getDueRecordsByVillage' : ActorMethod<[string], Array<DueRecord>>,
  'getLowStockMedicines' : ActorMethod<[], Array<MedicineRecord>>,
  'getLowStockSortedByExpiry' : ActorMethod<[], Array<MedicineRecord>>,
  'getLowStockSortedByQuantity' : ActorMethod<[], Array<MedicineRecord>>,
  'getMedicine' : ActorMethod<[bigint], MedicineRecord>,
  'getMedicinesByBrand' : ActorMethod<[string], Array<MedicineRecord>>,
  'getMedicinesByType' : ActorMethod<[string], Array<MedicineRecord>>,
  'getMedicinesNearExpiry' : ActorMethod<[bigint], Array<MedicineRecord>>,
  'getPurchasesByDateRange' : ActorMethod<[Time, Time], Array<PurchaseRecord>>,
  'getSalesByDateRange' : ActorMethod<[Time, Time], Array<SaleRecord>>,
  'markDueAsPaid' : ActorMethod<[bigint], undefined>,
  'updateDueRecord' : ActorMethod<[bigint, DueRecord], undefined>,
  'updateMedicine' : ActorMethod<[bigint, MedicineRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];