/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DueRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'date' : Time,
  'neighborhood' : IDL.Text,
  'fatherName' : IDL.Text,
  'village' : IDL.Text,
  'itemType' : IDL.Text,
  'quantity' : IDL.Nat,
  'mobile' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'medicineId' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const MedicineRecord = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'expiryDate' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'minStockAlert' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'itemType' : IDL.Text,
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'supplierName' : IDL.Text,
  'date' : Time,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'medicineId' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const SaleRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Opt(IDL.Text),
  'date' : Time,
  'invoiceNumber' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'medicineId' : IDL.Nat,
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDueRecord' : IDL.Func([DueRecord], [IDL.Nat], []),
  'addMedicine' : IDL.Func([MedicineRecord], [IDL.Nat], []),
  'createPurchase' : IDL.Func([PurchaseRecord], [IDL.Nat], []),
  'createSale' : IDL.Func([SaleRecord], [IDL.Nat], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
  'getAllDueRecords' : IDL.Func([], [IDL.Vec(DueRecord)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(MedicineRecord)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
  'getDueRecord' : IDL.Func([IDL.Nat], [DueRecord], ['query']),
  'getDueRecordsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DueRecord)],
      ['query'],
    ),
  'getDueRecordsByVillage' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DueRecord)],
      ['query'],
    ),
  'getLowStockMedicines' : IDL.Func([], [IDL.Vec(MedicineRecord)], ['query']),
  'getLowStockSortedByExpiry' : IDL.Func(
      [],
      [IDL.Vec(MedicineRecord)],
      ['query'],
    ),
  'getLowStockSortedByQuantity' : IDL.Func(
      [],
      [IDL.Vec(MedicineRecord)],
      ['query'],
    ),
  'getMedicine' : IDL.Func([IDL.Nat], [MedicineRecord], ['query']),
  'getMedicinesByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicineRecord)],
      ['query'],
    ),
  'getMedicinesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicineRecord)],
      ['query'],
    ),
  'getMedicinesNearExpiry' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MedicineRecord)],
      ['query'],
    ),
  'getPurchasesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'getSalesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(SaleRecord)],
      ['query'],
    ),
  'markDueAsPaid' : IDL.Func([IDL.Nat], [], []),
  'updateDueRecord' : IDL.Func([IDL.Nat, DueRecord], [], []),
  'updateMedicine' : IDL.Func([IDL.Nat, MedicineRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DueRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'date' : Time,
    'neighborhood' : IDL.Text,
    'fatherName' : IDL.Text,
    'village' : IDL.Text,
    'itemType' : IDL.Text,
    'quantity' : IDL.Nat,
    'mobile' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'medicineId' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const MedicineRecord = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'expiryDate' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'minStockAlert' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'itemType' : IDL.Text,
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'supplierName' : IDL.Text,
    'date' : Time,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'medicineId' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const SaleRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Opt(IDL.Text),
    'date' : Time,
    'invoiceNumber' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'medicineId' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    'addDueRecord' : IDL.Func([DueRecord], [IDL.Nat], []),
    'addMedicine' : IDL.Func([MedicineRecord], [IDL.Nat], []),
    'createPurchase' : IDL.Func([PurchaseRecord], [IDL.Nat], []),
    'createSale' : IDL.Func([SaleRecord], [IDL.Nat], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
    'getAllDueRecords' : IDL.Func([], [IDL.Vec(DueRecord)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(MedicineRecord)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(SaleRecord)], ['query']),
    'getDueRecord' : IDL.Func([IDL.Nat], [DueRecord], ['query']),
    'getDueRecordsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DueRecord)],
        ['query'],
      ),
    'getDueRecordsByVillage' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DueRecord)],
        ['query'],
      ),
    'getLowStockMedicines' : IDL.Func([], [IDL.Vec(MedicineRecord)], ['query']),
    'getLowStockSortedByExpiry' : IDL.Func(
        [],
        [IDL.Vec(MedicineRecord)],
        ['query'],
      ),
    'getLowStockSortedByQuantity' : IDL.Func(
        [],
        [IDL.Vec(MedicineRecord)],
        ['query'],
      ),
    'getMedicine' : IDL.Func([IDL.Nat], [MedicineRecord], ['query']),
    'getMedicinesByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicineRecord)],
        ['query'],
      ),
    'getMedicinesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicineRecord)],
        ['query'],
      ),
    'getMedicinesNearExpiry' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MedicineRecord)],
        ['query'],
      ),
    'getPurchasesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getSalesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(SaleRecord)],
        ['query'],
      ),
    'markDueAsPaid' : IDL.Func([IDL.Nat], [], []),
    'updateDueRecord' : IDL.Func([IDL.Nat, DueRecord], [], []),
    'updateMedicine' : IDL.Func([IDL.Nat, MedicineRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };