/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MedicineRecord {
    id: bigint;
    purchasePrice: bigint;
    expiryDate: Time;
    name: string;
    createdAt: Time;
    minStockAlert: bigint;
    sellingPrice: bigint;
    itemType: string;
    quantity: bigint;
    brand: string;
}
export type Time = bigint;
export interface DueRecord {
    id: bigint;
    customerName: string;
    status: string;
    date: Time;
    neighborhood: string;
    fatherName: string;
    village: string;
    itemType: string;
    quantity: bigint;
    mobile: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}
export interface PurchaseRecord {
    id: bigint;
    supplierName: string;
    date: Time;
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}
export interface SaleRecord {
    id: bigint;
    customerName?: string;
    date: Time;
    invoiceNumber: bigint;
    notes?: string;
    quantity: bigint;
    brand: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}
export interface backendInterface {
    addDueRecord(input: DueRecord): Promise<bigint>;
    addMedicine(input: MedicineRecord): Promise<bigint>;
    createPurchase(input: PurchaseRecord): Promise<bigint>;
    createSale(input: SaleRecord): Promise<bigint>;
    deleteMedicine(medicineId: bigint): Promise<void>;
    getAllDueRecords(): Promise<Array<DueRecord>>;
    getAllMedicines(): Promise<Array<MedicineRecord>>;
    getAllPurchases(): Promise<Array<PurchaseRecord>>;
    getAllSales(): Promise<Array<SaleRecord>>;
    getDueRecord(dueId: bigint): Promise<DueRecord>;
    getDueRecordsByStatus(status: string): Promise<Array<DueRecord>>;
    getDueRecordsByVillage(village: string): Promise<Array<DueRecord>>;
    getLowStockMedicines(): Promise<Array<MedicineRecord>>;
    getLowStockSortedByExpiry(): Promise<Array<MedicineRecord>>;
    getLowStockSortedByQuantity(): Promise<Array<MedicineRecord>>;
    getMedicine(medicineId: bigint): Promise<MedicineRecord>;
    getMedicinesByBrand(brand: string): Promise<Array<MedicineRecord>>;
    getMedicinesByType(itemType: string): Promise<Array<MedicineRecord>>;
    getMedicinesNearExpiry(days: bigint): Promise<Array<MedicineRecord>>;
    getPurchasesByDateRange(startDate: Time, endDate: Time): Promise<Array<PurchaseRecord>>;
    getSalesByDateRange(startDate: Time, endDate: Time): Promise<Array<SaleRecord>>;
    markDueAsPaid(dueId: bigint): Promise<void>;
    updateDueRecord(dueId: bigint, input: DueRecord): Promise<void>;
    updateMedicine(medicineId: bigint, input: MedicineRecord): Promise<void>;
}
import type { SaleRecord as _SaleRecord, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDueRecord(arg0: DueRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDueRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDueRecord(arg0);
            return result;
        }
    }
    async addMedicine(arg0: MedicineRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0);
            return result;
        }
    }
    async createPurchase(arg0: PurchaseRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchase(arg0);
            return result;
        }
    }
    async createSale(arg0: SaleRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSale(to_candid_SaleRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSale(to_candid_SaleRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMedicine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getAllDueRecords(): Promise<Array<DueRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDueRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDueRecords();
            return result;
        }
    }
    async getAllMedicines(): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return result;
        }
    }
    async getAllSales(): Promise<Array<SaleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDueRecord(arg0: bigint): Promise<DueRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueRecord(arg0);
            return result;
        }
    }
    async getDueRecordsByStatus(arg0: string): Promise<Array<DueRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueRecordsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueRecordsByStatus(arg0);
            return result;
        }
    }
    async getDueRecordsByVillage(arg0: string): Promise<Array<DueRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueRecordsByVillage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueRecordsByVillage(arg0);
            return result;
        }
    }
    async getLowStockMedicines(): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockMedicines();
            return result;
        }
    }
    async getLowStockSortedByExpiry(): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockSortedByExpiry();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockSortedByExpiry();
            return result;
        }
    }
    async getLowStockSortedByQuantity(): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockSortedByQuantity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockSortedByQuantity();
            return result;
        }
    }
    async getMedicine(arg0: bigint): Promise<MedicineRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return result;
        }
    }
    async getMedicinesByBrand(arg0: string): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByBrand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByBrand(arg0);
            return result;
        }
    }
    async getMedicinesByType(arg0: string): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByType(arg0);
            return result;
        }
    }
    async getMedicinesNearExpiry(arg0: bigint): Promise<Array<MedicineRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesNearExpiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesNearExpiry(arg0);
            return result;
        }
    }
    async getPurchasesByDateRange(arg0: Time, arg1: Time): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchasesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchasesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getSalesByDateRange(arg0: Time, arg1: Time): Promise<Array<SaleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByDateRange(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByDateRange(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async markDueAsPaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDueAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDueAsPaid(arg0);
            return result;
        }
    }
    async updateDueRecord(arg0: bigint, arg1: DueRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDueRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDueRecord(arg0, arg1);
            return result;
        }
    }
    async updateMedicine(arg0: bigint, arg1: MedicineRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, arg1);
            return result;
        }
    }
}
function from_candid_SaleRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleRecord): SaleRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: [] | [string];
    date: _Time;
    invoiceNumber: bigint;
    notes: [] | [string];
    quantity: bigint;
    brand: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}): {
    id: bigint;
    customerName?: string;
    date: Time;
    invoiceNumber: bigint;
    notes?: string;
    quantity: bigint;
    brand: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.customerName)),
        date: value.date,
        invoiceNumber: value.invoiceNumber,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        brand: value.brand,
        unitPrice: value.unitPrice,
        totalPrice: value.totalPrice,
        medicineId: value.medicineId,
        medicineName: value.medicineName
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaleRecord>): Array<SaleRecord> {
    return value.map((x)=>from_candid_SaleRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SaleRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleRecord): _SaleRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName?: string;
    date: Time;
    invoiceNumber: bigint;
    notes?: string;
    quantity: bigint;
    brand: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}): {
    id: bigint;
    customerName: [] | [string];
    date: _Time;
    invoiceNumber: bigint;
    notes: [] | [string];
    quantity: bigint;
    brand: string;
    unitPrice: bigint;
    totalPrice: bigint;
    medicineId: bigint;
    medicineName: string;
} {
    return {
        id: value.id,
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        date: value.date,
        invoiceNumber: value.invoiceNumber,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        brand: value.brand,
        unitPrice: value.unitPrice,
        totalPrice: value.totalPrice,
        medicineId: value.medicineId,
        medicineName: value.medicineName
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
